### PR TITLE
fix(maps): pin location

### LINKED ISSUE #176: Maps: Location PIN misbehaves when zooming
## Description

When I zoom in and out on the map in the right sidebar, the pin marking the location of an image moves over the world map as I zoom out, see screenshots.

## Steps to reproduce

1. Upload an image with geo-location
2. Do a page reload (because location metadata is only available on a subsequent propfind, we have no SSE for that)
3. Select the image
4. Open the right sidebar
5. Zoom out on the map multiple times

## Expected behaviour

The pin always marks the correct location

## Actual behaviour

As I zoom out, the pin moves over the world map, see screenshots below.

## Screenshots

Starting somewhere in Italy:

Image

Now we're in the water:

Image

Whoopsie, Africa:

Image

### PR DESCRIPTION
**Pull request by dschmidt**
## Description

Fix weird pin behavior on zoom.

## Related Issue

- Fixes #176 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bugfix
- [ ] Enhancement (a change that doesn't break existing code or deployments)
- [ ] Breaking change (a modification that affects current functionality)
- [ ] Technical debt (addressing code that needs refactoring or improvements)
- [ ] Tests (adding or improving tests)
- [ ] Documentation (updates or additions to documentation)
- [ ] Maintenance (like dependency updates or tooling adjustments)

### CODE REVIEW

File: packages/web-app-maps/src/components/LocationFolderView.vue [hunk 1]
```diff
@@ -10,70 +10,36 @@
...
   resources: Resource[]
   applicationConfig: Record<string, any>
 }>()
 
 const { $gettext } = useGettext()
-const { createMap, createPinIcon } = useLeaflet()
+const { createMap } = useLeaflet()
 const leafletElement = ref<HTMLElement | null>(null)
 const initialized = ref(false)
+const mapObject = ref<L.Map | null>(null)
```
Comment (JammingBen) [inline packages/web-app-maps/src/components/LocationFolderView.vue]: Giving it `null` initially changes the type, maybe you remember the issue we had some time ago 😬 

```suggestion
const mapObject = ref<L.Map | null>()
```

Or maybe just remove `null` from the type as well? Since it will be typed `L.Map | undefined` implicitly.

```suggestion
const mapObject = ref<L.Map>()
```

File: packages/web-app-maps/src/components/LocationPanel.vue [hunk 2]
```diff
@@ -3,72 +3,38 @@
...
   applicationConfig: Record<string, any>
 }>()
 
-const { createMap, createPinIcon } = useLeaflet()
+const { createMap } = useLeaflet()
 const { onPanelActive } = useSideBar()
 
 const leafletElement = ref<HTMLElement | null>(null)
 const initialized = ref(false)
+const mapObject = ref<L.Map | null>(null)
```
Comment (JammingBen) [inline packages/web-app-maps/src/components/LocationPanel.vue]: Same here.
